# Generated by Django 5.2.8 on 2026-04-07 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_format', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('total_columns', models.IntegerField(default=0)),
                ('missing_values', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('preview_columns', models.JSONField(blank=True, default=list)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remove_duplicates', models.BooleanField(default=True)),
                ('fix_missing_values', models.BooleanField(default=True)),
                ('standardize_headers', models.BooleanField(default=True)),
                ('trim_whitespace', models.BooleanField(default=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('duplicates_removed', models.IntegerField(default=0)),
                ('missing_values_fixed', models.IntegerField(default=0)),
                ('headers_standardized', models.IntegerField(default=0)),
                ('whitespace_trimmed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_jobs', to='core.datafile')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_jobs', to='core.datafile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
